### ISSUE TITLE
P8 (post-royal-assent) content changes (non-calculator function)

### ISSUE THREAD

**Issue by LMElston** [gc-proto/covid-19-guidance#123]
Changes to the content once the changes announced receive royal assent:

Landing page (first draft in Word, attached below)

- Update announcement re. changes to the program, link to what the changes are

[What the changes are](http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/cews-what-changes.html) 

- Change top tabs to give overview of changes by date of change instead of applicable periods
- Write overview of latest changes for points in tab
- Determine what should be in the body of the page--consider a mention of how to change a return because of the retroactive changes
- Write P8-10 examples

Who can apply (first draft in Word, attached below & sent to LPRAB)

- Tab labels (at a minimum)
- Check wording of asset purchasing criteria
- Check wording of payroll criteria

[Periods you can apply for ](http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/cews-periods-apply.html)

- Updated format of page to more dynamic, tested version
- Added P10 
- Added deadlines to all periods
- Added intro text

Which of your employees are eligible 

- Update pre-crisis pay calculation section with new option for P5+
- Remove "new" tag from previous updates

Calculate your subsidy amount 

- Update/remove disclaimer text re P8
- Add text re. top-up safe harbour in revenue drop box (and maybe top of page)
- Confirm pop-up explanation of baseline remuneration calculation makes sense/works (fix footnote link)
- Update version table with new spreadsheet info
- Update line language to match any application form changes
- Add new P5-6 spreadsheet with retroactive changes for baseline remuneration
- Add new P7+ spreadsheet with changes to P8 and baseline remuneration (P9-10 changes to follow)

How the revenue drop and subsidy rate are calculated

- Top-up calculation change for P8+
- Reorganize/re-label page according to changes [Miguel has an idea]
- Add announced base rates for P9+

[How the subsidy is calculated ](http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/cews-how-subsidy-calculated.html) (first draft in Word, attached below & sent to LPRAB)

- Considered separating P9+ from P7-8 but it is probably not necessary as the mechanics are basically the same
- Added P10 to label
- Added P9 calculation for employees on leave with pay (but may be a separate update; see comment)

How to apply --> potentially out of scope for this release

- Consider mentioning changing a return

After you apply --> potentially out of scope for this release

- TBD if breakdown will launch with this or P9 opening
- Maybe: enhanced information about changing an application, specifically about how to change an election you made on a previous return

Application guide

- Yes, to match any form changes (Lisa checking with Jeff/Gary/Jules)

FAQs

- Yes (will come from LPRAB)

**Comment by LMElston** [comment]
Mock-up of [Periods you can apply for](http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/cews-periods-apply.html) using the tested design from another benefit.

**Comment by LMElston** [comment]
The changes for How the subsidy is calculated will need to wait until further information has been released about the treatment of employees on leave for P9+. If this information is not included in the bill, this can be a separate update from the rest of the changes for Nov. 16.

**Comment by LMElston** [comment]
Questions for @Christopher-O , @Alireme , @qusai-barakat, @lbelmore-gc , and @Borges-Porteous (if you have time):

- Does the **Periods you can apply for** page function and look ok in the GitHub mockup? Any recommended changes or is this one good to go to LPRAB for review?

For **What the changes are**, I think this page should serve as a sort of "news" page, more than an overview page, but I feel like as I make changes, I'm removing the reasons people liked this page in testing.

- Do you agree with the purpose of this page?
- I think it is still beneficial to list the previous changes that were announced, so people have a way of comparing. Although it's not the majority of our users that will want a more high-level view of the changes, there are some people who would benefit from having a place where they can see basically what changes were introduced at different times. Prove me wrong! :)
- What is the best way to label the changes in the tabs at the top? Are tabs still the best way to go? If the dates are not helpful, what would be?
- Is it useful to list things like the base rate, top-up rate, and max per employee on this page? They are definitely related to recently-announced changes, but is it helpful to have this info here?
- Should we keep or remove the process summary at the bottom? We discussed that it is redundant, but then it was mentioned that people found the page helpful. Was this part of the page helpful in particular?

**Comment by lbelmore-gc** [comment]
Hey @LMElston - thanks for putting this all together. 

For the periods you can apply for, I like the drop down as opposed to the large scrolling list. 

This new layout now highlights the current and next period. 
Is clear that they can apply or all past period and should we be also indicating the deadlines to apply? Maybe just a line of text with the All period drop down list. 

@Christopher-O @Alireme @qusai-barakat  - thoughts??

**Comment by Christopher-O** [comment]
@LMElston @lbelmore-gc  I think the periods should still be listed, but perhaps in an expand/hide.  Fieldflows should not hide information by default whenever possible (due to people not using javascript).   There is arguments within TBS about whether that is required (depending on the information), but as a primary source of providing the content (periods), I think it's a great idea.  I agree with Lisa and I don't feel that the current/next period (in the expand/hides) are really required any more since the dropdown does a good job that already.  It also means more work for WebDev to change.  I would recommend that the current period simply be indicated like such
![image](https://user-images.githubusercontent.com/9367162/98031423-b3635780-1dcf-11eb-9b2b-02d02ca1d8a0.png)

As for "what the changes are" tabs are a bit dangerous because once you have more than 4 they may not fit on the single line.  I feel this page is becoming too much like an FAQ or a quick overview....I would rather put actual content and examples at the point of need, and if need be, just simply link to them.  As the periods continue to evolve and change, I feel that this would be suited more as a news feed with the newest information at top.  Not only would that indicate to someone when changes have been made by an actual date (rather than having to determine first what period we are currently in), but also keep the newest information at the top.    The header "How you apply" doesn't make sense on a page about "changes" as that pretty much has not changed since period 5....and only regarding the online calculator, so it seems like redundency.

**Comment by LMElston** [comment]
> Is clear that they can apply or all past period and should we be also indicating the deadlines to apply? Maybe just a line of text with the All period drop down list.
@lbelmore-gc the deadline is listed when you select a period--are you thinking we should also say something general before the drop-down like "the deadline to apply is the later of either 180 days after the end of the period or January 31, 2021, whichever comes first"?

> I think the periods should still be listed, but perhaps in an expand/hide
@Christopher-O It makes sense that we shouldn't hide this in a fieldflow--for this idea, are you picturing having the expand hide list immediately before the field flow? I'm good with removing the "Current period" and "upcoming period" bits.

> As for "what the changes are"
@Christopher-O I am interested in what it might look like to reformat this as a news page--I'd like to hear from @Alireme before I make any changes, in case there are user reasons to keep other content like examples/explanations on the page that I have forgotten. If we do change the formatting, are you available to do a mockup on GH?

Just so everyone knows, I've committed to getting all the CEWS pages to LPRAB by Friday so they have time to review/correct. So I appreciate the speedy input :)

**Comment by lbelmore-gc** [comment]
@LMElston - for the deadlines - yes I was thinking that there should be a line to highlight the 180 day deadline. And of course as periods become expired we would update accordingly.

**Comment by Christopher-O** [comment]
@LMElston  I think we can still have the fieldflow AND the expand/hide.  The fieldflow would clean things up and not pollute with information not needed (we did that for a CERB fieldflow).  I know the original idea was to have expand hides in expand hides, but it was abandoned as it was a bit "clunky".  
For the "what the changes are, the content and styling could stay similar, we just parse it up more by dates rather than mixing in a variety of changes into types.  I agree I would like to get @Alireme thoughts on what worked exactly with what the changes are so we don't risk losing that engagement.

**Comment by LMElston** [comment]
Attaching some of the proposed changes drafted in Word docs here in case anyone needs access to them (not yet reviewed by LPRAB).
[CanadaEmergencyWageSubsidy_Nov16.docx](https://github.com/gc-proto/covid-19-guidance/files/5484514/CanadaEmergencyWageSubsidy_Nov16.docx)
[Whocanapply_Nov16.docx](https://github.com/gc-proto/covid-19-guidance/files/5484522/Whocanapply_Nov16.docx)
[Howthesubsidyiscalculated_Nov16.docx](https://github.com/gc-proto/covid-19-guidance/files/5484523/Howthesubsidyiscalculated_Nov16.docx)

**Comment by LMElston** [comment]
Published Nov. 23
