### ISSUE TITLE
P2 content updates

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#162]
Period 2 opens on Monday Nov 30th

- updating drop downs on 3 pages (periods you can claim, calculate your subsidy, how to apply)
- months in calculator page need to be updated
- Q&A messaging on Contact us

**Comment by tanyafowler** [comment]
P2 changes have been written up for Web dev. Ticket has not yet been submitted.

Ticket will include:
- How to apply
- Calculate your subsidy
- Periods you can apply for

Ticket will not include Contact us update, since timing for this is TBD depending on Robyn Macdonald and Jennifer Clark from Consultations and Stakeholder Engagement. 

Received updated French translation from J-F.

Noticed How to apply page should include all periods in drop down, not just open ones, but will confirm P3 date with Lisa before making that change.

Next steps:
- submit P2 ticket to PubHub
- email Robyn/Jennifer > send updated content/design treatment (adding registration button), and ask about timelines - for Nov 30, during Nov 30, later?
- confirm P3 date and add it to drop down > Alert will pop up that says it's not yet open

**Comment by tanyafowler** [comment]
P2 changes were published Monday November 30. Closing issue.
