### ISSUE TITLE
CEWS changes for August 17

### ISSUE THREAD

**Issue by LMElston** [gc-proto/covid-19-guidance#69]
Period 5 applications open August 17. Here are some things that will need to be updated:
- the **application guide** will be updated and will be coming from CVB for publishing (Alexandra MacLean is the leadership contact in case it is not received; Kathryn Ransome and Julianne Lacroix are working on the guide). It may benefit from a plain language review when it comes in, if possible. Last I saw they are planning to update the existing guide rather than create a new one for period 5+.
- the **attestation forms** are being updated so the links to those will need to change. Forms and pubs recently added these as pages rather than PDFs but I'm not sure whether we should link to the page or the PDF. They are also not sure yet if there are supposed to be separate attestation forms for periods 1 to 4 and periods 5 and later (the elections are different). These attestation forms are linked in three places:
      - How to apply
      - Attestation section in the application guide
      - FAQ (I think it's at least twice there, using the word "elect" as the link text)
- the **alert on the landing page** will need to be updated 
- on the page **Periods you can apply for** period 5 will need to be moved to the open section and the application date changed to a "yes" (like periods 1 to 4)
- on **How to apply** the period selection for claim period 5 needs to indicate that you can apply for that period

**Comment by LMElston** [comment]
Forms and pubs link to the attestation form: 
https://www.canada.ca/en/revenue-agency/services/forms-publications/forms/rc661.html
https://www.canada.ca/fr/agence-revenu/services/formulaires-publications/formulaires/rc661.html

**Comment by tanyafowler** [comment]
PubHub ticket number 206730 submitted to update attestation form links on:

- How to apply
- Application guide
- FAQs

Link to ticket: http://lse-esl.ec.rc.gc.ca/pab-dgap/pubhub/pub/cp/consultRequest.action?id=206730 

Ticket instructions are to link to forms and publications HTML page rather than directly to PDF. Also asked that web dev search for other links to the PDF and send me the report, and that they specifically search the code for FAQs for any other references to the PDF and update them to the HTML page.

**Comment by tanyafowler** [comment]
PubHub ticket number 206730 submitted to update attestation form links on:

- How to apply
- Application guide
- FAQs

Link to ticket: http://lse-esl.ec.rc.gc.ca/pab-dgap/pubhub/pub/cp/consultRequest.action?id=206730 

Ticket instructions are to link to forms and publications HTML page rather than directly to PDF. Also asked that web dev search for other links to the PDF and send me the report, and that they specifically search the code for FAQs for any other references to the PDF and update them to the HTML page.

**Comment by tanyafowler** [comment]
PubHub ticket number 206730 submitted to update attestation form links on:

- How to apply
- Application guide
- FAQs

Link to ticket: http://lse-esl.ec.rc.gc.ca/pab-dgap/pubhub/pub/cp/consultRequest.action?id=206730 

Ticket instructions are to link to forms and publications HTML page rather than directly to PDF. Also asked that web dev search for other links to the PDF and send me the report, and that they specifically search the code for FAQs for any other references to the PDF and update them to the HTML page.

**Comment by tanyafowler** [comment]
PubHub ticket number 206730 submitted to update attestation form links on:

- How to apply
- Application guide
- FAQs

Link to ticket: http://lse-esl.ec.rc.gc.ca/pab-dgap/pubhub/pub/cp/consultRequest.action?id=206730 

Ticket instructions are to link to forms and publications HTML page rather than directly to PDF. Also asked that web dev search for other links to the PDF and send me the report, and that they specifically search the code for FAQs for any other references to the PDF and update them to the HTML page.

**Comment by tanyafowler** [comment]
PubHub ticket number 206730 submitted to update attestation form links on:

- How to apply
- Application guide
- FAQs

Link to ticket: http://lse-esl.ec.rc.gc.ca/pab-dgap/pubhub/pub/cp/consultRequest.action?id=206730 

Ticket instructions are to link to forms and publications HTML page rather than directly to PDF. Also asked that web dev search for other links to the PDF and send me the report, and that they specifically search the code for FAQs for any other references to the PDF and update them to the HTML page.

**Comment by tanyafowler** [comment]
PubHub ticket number 206730 submitted to update attestation form links on:

- How to apply
- Application guide
- FAQs

Link to ticket: http://lse-esl.ec.rc.gc.ca/pab-dgap/pubhub/pub/cp/consultRequest.action?id=206730 

Ticket instructions are to link to forms and publications HTML page rather than directly to PDF. Also asked that web dev search for other links to the PDF and send me the report, and that they specifically search the code for FAQs for any other references to the PDF and update them to the HTML page.

**Comment by tanyafowler** [comment]
Will also need to follow up with Mathieu to approve unpublishing 2 old pages from old CEWS structure. Asked him to leave them up for now as I review the updated Application guide draft to make sure I can find the equivalent content if they've referenced old pages.

**Comment by tanyafowler** [comment]
Mathieu has unpublished 2 old pages from old CEWS structure and has temporarily re-published them to preview for me. This is so I can compare the links in the updated app guide Word doc to see what the content author wanted to point to and find the equivalent content in the new site.

**Comment by tanyafowler** [comment]
Preview links for the old pages referenced in previous comment are:
https://canada-preview.adobecqms.net/en/revenue-agency/services/subsidy/emergency-wage-subsidy/cews-who-eligible-employer.html 
https://canada-preview.adobecqms.net/en/revenue-agency/services/subsidy/emergency-wage-subsidy/cews-determine-eligible-employees.html

**Comment by tanyafowler** [comment]
Sent PubHub ticket 206777 to update Application guide with content received this afternoon from Kathryn Ransome (CVB). French and English docs received. I updated the links in the documents before attaching to ticket.

**Comment by tanyafowler** [comment]
Sent PubHub ticket 206843 to update CEWS landing page, Periods you can apply for, and How to apply for August 17. Requested preview links by 1 p.m. tomorrow (Friday) and advised updates will be published live on Monday August 17 at 8:00 a.m. ET.

**Comment by tanyafowler** [comment]
Ticket 206730 - to update attestation forms - was completed yesterday afternoon. Links to PDFs were removed and replaced with links to forms and pubs page:

https://www.canada.ca/en/revenue-agency/services/forms-publications/forms/rc661.html

**Comment by lbelmore-gc** [comment]
Aug 17th updates for period 5 applications open are complete. Closing this ticket
