### ISSUE TITLE
Print and save UX updates

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#82]
Updating the UX for the print option at the end of the calculator page.

The print and save button not being seen on the calculation summary - and we need to ensure it is clear before users go on to the next step and avoid any loss of their calculations.

http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/how-much.html

**Comment by lbelmore-gc** [comment]
The print button has been moved down. Can we also look at the content for this and update it to make sure it is clear.

Adding @tanyafowler @LMElston for this.

**Comment by lbelmore-gc** [comment]
@LMElston - any content need to ensure users understand that they need to print or save before moving on to the next step - or the calculations will be lost.

![image](https://user-images.githubusercontent.com/68651474/92517205-4d4dc000-f1e4-11ea-81ab-018378f8ce6b.png)

**Comment by Christopher-O** [comment]
@lbelmore-gc @LMElston  I think it might be good to get into the user's head of the print function as they do the final calculation 
![image](https://user-images.githubusercontent.com/9367162/92518310-5aaf7e00-f1d5-11ea-9f3b-92a9d785c7e4.png)

Rather than simply after the fact in the final calculation panel.  

We also want to avoid the phrase "save" as technically there is no  actual"save" feature...you can either print to a printer or to PDF.   If there was some sort of "save as" function in WET4 (to save directly as a PDF or another program file), then that would be logical to add that.  However that is not available at this time (seems to require a seperate script for that).

**Comment by lbelmore-gc** [comment]
@Christopher-O @LMElston - Yes it makes sense to not use the term "save" if we can't add that functionality.

Do you think we should add some text at the bottom before they go on to the next page to say something about how the calculations won't be saved once they leave the page?? To emphasize that this is the only chance to print

**Comment by Christopher-O** [comment]
@lbelmore-gc good point.  We do say that inside the privacy statement already as a warning, though that's not really a privacy statement. If we could avoid repetition, that would be great.  @LMElston I propose we move it out of the privacy statement and just above the button to calculate and print (I think putting it in the panel would clutter things up a bit too much).   

I don't think data in testing showed that people were leaving the page before they "printed" their statement, so this would only seem to be an option tweak correct?

**Comment by LMElston** [comment]
I understand wanting to avoid repetition but the mention of not saving information exists for 2 different reasons: 1, to reassure people that we are not keeping information they may consider private; 2, to prevent them from believing it will be saved if they come back to the page. I think we may need to repeat in slightly different language accordingly. Proposed text updates incoming shortly.

**Comment by Christopher-O** [comment]
@LMElston the first paragraph in the privacy statment already says that we will not retain the information, and that can stay. I only speak of the "warning" paragraph, which has nothing to do with privacy but rather that because the form will not save that data, it's best to print it.  If we were to keep it in the privacy statement, it should probably be re-phrased as it seems like a standalone statment, when infact it's a defacto result that we do not store the information that they may lose it if they leave the page.

**Comment by LMElston** [comment]
@Christopher-O I agree with moving the warning and keeping the first sentence. I thought that was supposed to be outside the privacy statement (just after it) originally anyway. I've tentatively moved it to the final summary box but it may merit being earlier on the page as well.

I'm confused about the placement of the print preview button before the summary, and why the summary doesn't include all the line numbers. As I'm working through the text I wonder if people will think the summary is the print preview and not click the button (as obvious as it seems)? Is that crazy?

**Comment by LMElston** [comment]
Ok! After speaking with @Christopher-O I believe we have some edits for your consideration.
Included in the attachment:
- updating language for "How the calculator helps you" based on Louis' suggestion
- removing 'warning' text from within the privacy statement
- adjusting lead-in text for calculation summary to tell people exactly what numbers they need and promoting the need to print the summary
- including the warning about saving information, previously in the privacy statement
- emphasizing (bold) line numbers from thorough summary at end, in case people are manually transcribing numbers instead of printing
- de-emphasizing final summary of CEWS claim table so it is less likely to be confused with the complete set of line numbers above, and re-naming it to show it is only summarizing the calculation (not the whole claim)
- removing links to how to apply page from within the summary so it is less tempting for people to click them and lose their information before they have printed
- removing final statement "you are now ready to use this information" from after calculation summary so it is more obvious that they need all the information in the thorough summary above (not just the calculation summary) to apply
[Calculate_your_subsidy_print_edits.docx](https://github.com/gc-proto/covid-19-guidance/files/5196481/Calculate_your_subsidy_print_edits.docx)

**Comment by tanyafowler** [comment]
@LMElston - edits look great. I'm making one suggested alternative for the Results section:

You are now ready to print these amounts to enter in your wage subsidy application

Suggestion: 
(**bold only added to highlight changes to your original, not intended as formatting choices**)

You are now ready to print these amounts **and** enter **them into** your wage subsidy application

**Comment by lbelmore-gc** [comment]
I like the changes! Great work guys!!!

I would like to move this item forward before the other UX updates on the list. Let me know when this is ready on github and/or preview and I can run it through approvals

**Comment by Christopher-O** [comment]
@LMElston @lbelmore-gc  did we want the warning about leaving the page before printing where it is in the word document or closer to the print preview button.  I'm fine either way, but per the message above 
![image](https://user-images.githubusercontent.com/9367162/92630798-973eb080-f28d-11ea-8f41-43aae2d3b360.png)

**Comment by LMElston** [comment]
@Christopher-O @lbelmore-gc I was thinking at the beginning of the summary, although it's going to depend on where people end up doing their reading vs. skimming, which I find a little hard to predict (for some people it would have been helpful at the top of the page, for example). I thought putting it ahead of the summary information could be useful for those people who don't intend to print (but copy out/screenshot the information), but should also catch the people who do intend to print.

**Comment by Christopher-O** [comment]
@LMElston @lbelmore-gc I'm fine with that, we may want to get Alex's opinions on it, however I don't think testing showed that there was a risk that a person misses out on printing the document and goes straight to apply, so either way I think we are not hindering anything.  Also per the print preview @cfarquharson made a point that having it where it is seems that it will only print the top portion of the overlay, rather than the entire panel.  Now that we have removed that statement, I have moved it to the bottom of the panel and left aligned it so it is a bit clearer that it will print everything.

**Comment by lbelmore-gc** [comment]
@LMElston @Christopher-O @tanyafowler 

Looks like we need to unbold the "and" and "them into" from the line:
You are now ready to print these amounts and enter them into your wage subsidy application

![image](https://user-images.githubusercontent.com/68651474/92647910-ac7c0500-f2b6-11ea-87cd-2e03eff231ca.png)

Also is there now a disconnect with the button and the text?? Or should there be an additional line with the print button to say calculations will be lost after next step?

@cfarquharson - thoughts?

**Comment by LMElston** [comment]
At a minimum I think we should remove the "You are now ready..." sentence from the Result alert. But yes I do think it belongs with the print button.

I still wonder if there is a way to present this as one summary rather than having the detailed section and then the math (I still worry the calculation summary may lead people to not realize they need to record lines A, AA, c1, etc.). Give me a minute or two to see if I can come up with something...

**Comment by Alireme** [comment]
Agree with LM. It's not part of your result and should be moved to the bottom with the print button if it's going to be included. This error really focuses on the "it's all one application" thing. The wording could be something like "Print your results to ensure you have them ready for the next step in your CEWS application" or "Print your CEWS summary as your results will not be carried into the next step of the application process". Then we're hand-holding through their perception of the process, rather than our own ideas of how it's two separate processes?

**Comment by LMElston** [comment]
![CEWS summary option 2](https://user-images.githubusercontent.com/63660698/92654137-67a79c80-f2bd-11ea-9ef8-309b5be41c8b.PNG)

Maybe we can merge the summaries, something like this?

**Comment by Alireme** [comment]
This is a little scary looking, but definitely places more focus on the lines required for the application, instead of just the calculation summary at the end.

**Comment by LMElston** [comment]
It might be too significant a change for right now--if so, we could just move the 'You are now ready' line to the end, above the print preview button.

It would at least resolve the cognitive issue I'm having with the two summaries, and would also make the amounts you need to enter forlines A-c3 a little easier to scan for (rather than them being at the ends of sentences). But it might introduce other issues I haven't thought of.

**Comment by Christopher-O** [comment]
@LMElston @Alireme @lbelmore-gc  I have moved that statement above the print button.  
As per @LMElston screen shot, It would be nice to sort of combine both the line and the math, however I feel it might be taking up too much of the weight (calculation and what numbers to add, but that now seems secondary).  Also this would look really awkward in mobile.

**Comment by Christopher-O** [comment]
@LMElston now that we have moved the print button below, I wonder if the phrase at the top should be refined.  With the statement "Print and keep this record", if a person was to use the print button on their browser, they would get the entire webpage, which is not what they need.  Having the print preview button next to the text made it an easy way to signal they could use that function to target the line items only.   

Maybe we should change it slightly to
-Print and keep this record using the print preview button below 
or
- Print and keep this record (using the print preview button at the end of the summary)

or a variation of the two.

**Comment by LMElston** [comment]
The first option is fine by me @Christopher-O

**Comment by LMElston** [comment]
> As per @LMElston screen shot, It would be nice to sort of combine both the line and the math, however I feel it might be taking up too much of the weight (calculation and what numbers to add, but that now seems secondary). Also this would look really awkward in mobile.

Maybe there's a better place for the calculation summary table than within the print summary? It is secondary information and kind of distracts from the line items needed for the application. But I do agree that showing the calculation for Line H is good to show people. Just can't think of exactly where :/

I don't think it's a total dealbreaker as-is (esp. given the timelines) but I do feel like there's a better solution we haven't landed on yet...

**Comment by Christopher-O** [comment]
@LMElston we can always hide it in an expand hide...we can also remove it from print as well with a class.

**Comment by lbelmore-gc** [comment]
Here are the screen shots of what it is on the test site now:

![image](https://user-images.githubusercontent.com/68651474/92732805-f27faa00-f344-11ea-9f6a-5042a677ccc4.png)

![image](https://user-images.githubusercontent.com/68651474/92732997-2955c000-f345-11ea-983a-09150c7475f8.png)



I like some of the ideas above with updating the summary layout but also wondering if it is too much of a change for now? 
Should the Warning go at the top where it is, or at the bottom with the button??

**Comment by LMElston** [comment]
> Should the Warning go at the top where it is, or at the bottom with the button??

@Alireme do you have thoughts on the placement of the warning text?

@Christopher-O  can we remove "and based on the following criteria" from the lead-in sentence?

**Comment by Christopher-O** [comment]
@lbelmore-gc @LMElston  @Alireme if testing showed at all where people migrated first in the panel area may give us a good indication where best to put the statement.   I will suggest that if the consensus is to put the statement by the button, I would change or drop the "Warning" statement as not to confuse users that the warning is about the button....rather the warning is about "not" pressing the button, which..if left would provide a mixed message.

**Comment by Alireme** [comment]
@LMElston @Christopher-O @lbelmore-gc Honestly I think it makes sense to have the warning be at the top of the calcualtor OUTSIDE the privacy statement. This is where people start inputting their data and therefore where they should be told to not leave the page because we won't save their work. Putting it at the bottom makes me think "Well now you tell me!"

**Comment by LMElston** [comment]
> @LMElston @Christopher-O @lbelmore-gc Honestly I think it makes sense to have the warning be at the top of the calcualtor OUTSIDE the privacy statement. This is where people start inputting their data and therefore where they should be told to not leave the page because we won't save their work. Putting it at the bottom makes me think "Well now you tell me!"

That placement works for me!

If we want to have it in both places we could say: "You are now ready to **print these amounts** so you can enter them into your wage subsidy application. Data is not saved on this page. If you leave this page without printing you will need to enter your information again."

**Comment by Alireme** [comment]
@LMElston I'm happy with that!

**Comment by Christopher-O** [comment]
@lbelmore-gc @LMElston @Alireme  Those changes have been made.

**Comment by lbelmore-gc** [comment]
@LMElston @tanyafowler - do we need translations for these?

**Comment by LMElston** [comment]
Commenting to add the translations that have already been completed by J-F:

- updated text of "How the calculator helps you" 
- updated text of "Before you start" 
- changes to summary/print preview panel
[Calculate your subsidy amount_Sept 11 changes.docx](https://github.com/gc-proto/covid-19-guidance/files/5211251/Calculate.your.subsidy.amount_Sept.11.changes.docx)
[ssuc-calculez-montant-subvention_sept11changes_JFB.docx](https://github.com/gc-proto/covid-19-guidance/files/5211253/ssuc-calculez-montant-subvention_sept11changes_JFB.docx)


Not yet translated (but on this page):
- CPP/EI validation error message
- 2 new button texts in employee summary area
- "Employee name or alias"

**Comment by tanyafowler** [comment]
Print button and disclaimers and the UX update for the How the calculator helps you steps are now live - PubHub ticket # 208367 completed today. 

I have the translations for the 3 items @LMElston identified as outstanding but those changes have not yet been approved. Not closing this issue yet as there are still items that need to be completed. Might move those to a new issue - if I do I'll update and close this one.

**Comment by lbelmore-gc** [comment]
this is now live - closing ticket
