### ISSUE TITLE
Option to remove employee from calculations

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#83]
The calculator currently doesn't allow you to remove an employee once you have added in the info.

It has been suggested through testing that people need the ability to remove an employee from the list if errors are made.

Need to add an option to remove and employee.

**Comment by Michel-Tremblay** [comment]
I've merged the changes for this feature into [how-much.html](http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/how-much.html)

**Comment by Borges-Porteous** [comment]
@lbelmore-gc sorry, I didn't explain well at the status this morning. The changes I made were purely on the math side for the online calculator, and allowing options/months for periods 7-9. @Michel-Tremblay and @Christopher-O have been leading the functionality update for removing employees, refreshing the form and validation.

I know Michel has been working in the version where the changes for 7-9 math were made, so with his changes in how-much.html, we should have all the parts coming together! Thanks Michel!

**Comment by Christopher-O** [comment]
@lbelmore-gc I believe this can be closed as we have added the feature

**Comment by lbelmore-gc** [comment]
Thanks Chris

Should there be an option to remove employee 1? I see the button for employee 2 and onwards but not employee 1

**Comment by Christopher-O** [comment]
@lbelmore-gc  I don't know if the script to make sure at least one employee is not allowed to be deleted (hense having no employees), may be tricky.  I think it might be something of an edge case scenario.   

@Michel-Tremblay what are your thoughts on that? The script would have to add a remove button to employee 1 if another employee is added, removed if the employee 2, 3, etc was all deleted (and only employee 1 was left), or if employee 1 was deleted and not employee 2, then the remove button would have to be hidden for that employee (employee 2).  Basically there can never be 0 employees, but employee 1 could be removed if there was more than one employee.  

If it requires more testing and bug fixes, then I would recommend it not be implimented at this time, and could be looked at as a future iteration.  For now, having the remove function for all but the first employee would satisfy 99% of the cases where it was wanted/needed.

**Comment by Michel-Tremblay** [comment]
The script that generates a new employee form just clones the **first** employee form, and makes the necessary adjustments to id's rather that rebuilding each and every element, and piece of text. If the first employee can be removed, I would have to redo a fair amount of that script.

**Comment by Christopher-O** [comment]
@Michel-Tremblay thanks for the clarification.  @lbelmore-gc is having the current iteration sufficient at this time?  If so we can close this issue.

**Comment by Christopher-O** [comment]
@Michel-Tremblay @Borges-Porteous @lbelmore-gc @Michel-Tremblay As per the discussion in the meeting, is the simple solution that Employee one has a reset button only (not red just grey), to clear the data?  Anything more would require alot more script amendments and bug testing...which I don't know if that's the best use of resources for something that I don't know if it's a want rather than a need.

**Comment by Borges-Porteous** [comment]
> @Michel-Tremblay @Borges-Porteous @lbelmore-gc As per the discussion in the meeting, is the simple solution that Employee one has a reset (or clear data) button only (not red just grey), to clear the data? Anything more would require alot more script amendments and bug testing...which I don't know if that's the best use of resources for something that I don't know if it's a want rather than a need.

The question would be how the rest of the form treats a blank employee field. If someone resets employee 1, then finishes their calculation, do they have 1 extra active employee in their results?

**Comment by Christopher-O** [comment]
@Borges-Porteous yes that is a good point.  So maybe we don't add the clear/reset button for Employee 1 then and leave it as is.  

In hindsight there were many things we could of done differently (like make the add employee an independent feature rather than a clone, and for furture applications it would be easy to build this from scratch with validation that they have to have at least one employee before then can move forward...but unless @Michel-Tremblay says otherwise, I think re-engineering this for IMO edge case situations....would take a bit of time.    I totally agree that optimally everything David stated should be implimented.   Unfortunately I think we may be too far down the pipe on this...especially for a program that tentatively ends in January.

**Comment by Michel-Tremblay** [comment]
IMO, employee 1 _should_ be removable. The reason it isn't is because so much of the clone logic was done assuming that employee 1 would always exist that it would have been a lot more work to rewrite the clone logic and redo all the testing rather than assume that someone can enter their first employee's data correctly, or re-enter it if they made a mistake. 

Now it's more an exercise of rewriting the clone logic to look for the template based on a variable id rather than a static one, and this applies to updating each input element, and display element that is expected to be updated based on user input.

We would also need to test that the popup summary is updated correctly. 

So while I think it's the optimal solution, it's costly in terms of the QA required to ensure that everything is working correctly.

**Comment by Alireme** [comment]
My concern is that we're trying to solve something we aren't sure is even a problem. I haven't heard once that someone wants or needs to reset an employee, just the ability to delete.

**Comment by Borges-Porteous** [comment]
> IMO, employee 1 _should_ be removable. The reason it isn't is because so much of the clone logic was done assuming that employee 1 would always exist that it would have been a lot more work to rewrite the clone logic and redo all the testing rather than assume that someone can enter their first employee's data correctly, or re-enter it if they made a mistake.
> 
> Now it's more an exercise of rewriting the clone logic to look for the template based on a variable id rather than a static one, and this applies to updating each input element, and display element that is expected to be updated based on user input.
> 
> We would also need to test that the popup summary is updated correctly.
> 
> So while I think it's the optimal solution, it's costly in terms of development time and the QA required to ensure that everything is working correctly.
> 
> I would expect something like this to take me 1-2 full days to complete.

Sorry, this is probably a silly question - but why do we have to redo the logic? Can't we just 'hide' employee 1 and make employee 2 the first one? Would probably still require calling the clone function when there's no visible employee panels after one is deleted, so I don't know if it's easier, but thought I'd mention the idea anyways.

Also... this approach might require the number of active employees total in 2b to have a minus 1 as well, if it's based on the number of employee panels.

**Comment by Michel-Tremblay** [comment]
> 
> 
> > IMO, employee 1 _should_ be removable. The reason it isn't is because so much of the clone logic was done assuming that employee 1 would always exist that it would have been a lot more work to rewrite the clone logic and redo all the testing rather than assume that someone can enter their first employee's data correctly, or re-enter it if they made a mistake.
> > Now it's more an exercise of rewriting the clone logic to look for the template based on a variable id rather than a static one, and this applies to updating each input element, and display element that is expected to be updated based on user input.
> > We would also need to test that the popup summary is updated correctly.
> > So while I think it's the optimal solution, it's costly in terms of development time and the QA required to ensure that everything is working correctly.
> > I would expect something like this to take me 1-2 full days to complete.
> 
> Sorry, this is probably a silly question - but why do we have to redo the logic? Can't we just 'hide' employee 1 and make employee 2 the first one? Would probably still require calling the clone function when there's no visible employee panels after deleting one, so I don't know if it's easier, but thought I'd mention the idea anyways.
> 
> Also... this approach might require the number of active employees total in 2b to have a minus 1 as well, if it's based on the number of employee panels.

That's another approach, but now we're just choosing which part of this I'm re-writing. 

The benefit I usually think of when I think of removing > hiding is that by removing the elements, they are no longer in the DOM taking up the user's resources (RAM), and it makes the calculation logic simpler. 

It's an extreme case, but consider these steps as a user (while hiding unnecessary employees panels):
* add a bunch of employees to see how it works
* removes a couple employees
* then goes to use the form as normal (using 20 employees)

the calculator needs to correct for all those extra employees and associated inputs that could have been removed from the DOM
the code basically changes from 
```js
$(element).remove();
```
To this 
```js
$(element).addClass("hidden");
```
but it just becomes more baggage when doing the calculations. 

If we hide things, I'm not longer looking for elements that exist, but elements that exist and are not hidden in order to do calculations. The number of employees is no longer the number of actual employee forms, but the number of employee forms that are visible. The logic to remove the employees associated row from the table in the popup summary needs to now hide the row instead of removing it... I think it's about as equal if not more effort to be honest.

**Comment by LMElston** [comment]
@lbelmore-gc In case we want to alert the user that employee 1 cannot be deleted, a couple of short suggested text options:

"The first employee can't be removed"
"The first employee can be updated but not deleted"

I still think this text may be overkill (I think it should be obvious that you can't delete the person by virtue of the fact that the button is not there, and I really think we need to resist adding a single unnecessary word to the form) but just in case you do decide to add something, hopefully one of those will work.

**Comment by lbelmore-gc** [comment]
@Alireme @Christopher-O @cfarquharson - hoping to close the loop on this one (at least for this release)

Looking for your recommendation on the UX flow for the remove an employee feature. Currently employee 1 has no remove button, all other employees added have a red remove button. 

- add note in place of remove button - (Laura May provided examples above)
OR
- leave employee 1 as is with no remove option

**Comment by tanyafowler** [comment]
@Michel-Tremblay can you outline the code changes for the Remove button so I can include it in the PubHub ticket Mathieu will be working on? Thanks :)

**Comment by lbelmore-gc** [comment]
Hey guys - Just noticing an issue with the remove employee functionality.

If I add employees and then remove them - my summary still has the total I had before deleting. I had added 4 employees - deleted 2 and then my final summary shows 4 employees see below

![image](https://user-images.githubusercontent.com/68651474/93897073-a840e600-fcbf-11ea-90e5-7565ed511d5f.png)

**Comment by Michel-Tremblay** [comment]
Did you resubmit after removing employees?

**Comment by Christopher-O** [comment]
@Michel-Tremblay I just checked it and it's not that.  Even before sending the data below (clicking the button), I also added 4 employees, deleted two and it still says 4 employees...

**Comment by Michel-Tremblay** [comment]
the portion in the screenshot is updated by fields in 2b. if you dont recalculate, you wont see the changes. i thought this was what we agreed the functionality would be.

**Comment by Christopher-O** [comment]
But I didn't "recalcuate" I just "calculated".   I added the employees, removed two then pressed the calculate button....I didn't add employees press the calculate button, and then remove employees then expected the number of employees to auto change.

The recalcuation function is only if someone makes a change "after the fact" of pressing the button to send the data.  If they haven't set the data yet to step 2b, and made changes beforehand, that should be reflected when they press the button for the first time.

**Comment by Michel-Tremblay** [comment]
Just pushed an update that should fix this. Sorry for the confusion.

**Comment by Christopher-O** [comment]
@Michel-Tremblay thanks! I'll let him know.

**Comment by Christopher-O** [comment]
@lbelmore-gc @Michel-Tremblay the patch has been applied to preview and seems to be working now.

**Comment by lbelmore-gc** [comment]
Thanks guys! Looks good :)
